### PR TITLE
Fix bot not replying to issues with a body and no comments

### LINKED ISSUE #6: Bot wouldn't reply to an issue with a comment by author
If there is a comment such as this one, it would not reply to it.

### PR DESCRIPTION
**Pull request by TheSeanLavery**
fixes #6

### CODE REVIEW

**Comment by CodeReviewGPT** [comment]
This code looks good overall. However, there could be some improvements made to the formatting and style of the code. 

For example, the indentation is inconsistent, and the lines of code could be separated into multiple lines for readability. 

Also, the variable names could be improved for readability and the code could be refactored to make it more efficient.

Below is an example of the code with some of the improvements I mentioned:

```
# If the issue has no comments, generate a response to the issue body
else:
    # Generate a response to the issue body using OpenAI
    body = issue["body"]
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt="Write a response to this comment as if you are a Senior Developer:\n\n" + body + "\n\n",
        temperature=0.7,
        max_tokens=256,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )
    # Create a comment on the issue with the generated response
    comment

**Comment by CodeReviewGPT** [comment]
This code is good, but there is an opportunity to improve it. In particular, the prompt for the response should be more specific to indicate that it is coming from a Senior Developer. Additionally, the `temperature`, `max_tokens`, `top_p`, `frequency_penalty`, and `presence_penalty` parameters should be documented to explain their purpose. 

Below is a suggested revision of the code: 

```
# If the issue has no comments, generate a response to the issue body
else:
    # Generate a response to the issue body using OpenAI
    body = issue["body"]
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt="Write a response to this comment as if you are a Senior Developer:\n\n" + body + "\n\n",
        # Adjust the parameters to influence the quality of the response
        temperature=0.7,        # Higher values increase the creativity of the response
        max_tokens=256,         # Maximum number of tokens in the response
        top_p=1,                # The proportion of the tokens

**Comment by CodeReviewGPT** [comment]
Overall, the code looks good. However, some changes could be made to make it easier to read and understand. 

For example, the following lines of code:
```
model="text-davinci-003",
prompt="write a response to this comment:\n\n" + body + "\n\n",
temperature=0.7,
max_tokens=256,
top_p=1,
frequency_penalty=0,
presence_penalty=0
```

could be changed to: 
```
model="text-davinci-003",
prompt="write a response to this comment:\n\n" + body + "\n\n",
temperature=0.7,
max_tokens=256,
top_p=1,
frequency_penalty=0,
presence_penalty=0
```

to make it more readable and easier to understand. 

In addition, the following lines of code: 
```
# If the issue has no comments, generate a response to the issue body
else:
    # Generate a

**Comment by TheSeanLavery** [comment]
Looks good, but there is an error with how long you can reply. I made another issue and we can review that PR after this :)

**Comment by CodeReviewGPT** [comment]
Thanks for bringing this to my attention! I'll take a look at the other issue you mentioned and make sure to address it in the PR.

**Pull request merged**
