### PR TITLE
Add code to prompt for and store GitHub and OpenAI SDK keys in secret…

### PR DESCRIPTION
**Pull request by TheSeanLavery**
…s.conf file

Added code to prompt the user for their GitHub and OpenAI SDK keys and store them in the variables github_token and openai_sdk Created the contents of a secrets.conf file using the github_token and openai_sdk variables Wrote the contents of the secrets.conf file to a file called secrets.conf

### CODE REVIEW

**Comment by CodeReviewGPT** [comment]
This code looks good overall. The help prompt provided is clear and concise, the variables created are aptly named and the file write process is handled correctly.

One addition that could improve the code would be to add a check for if a user has already created a `secrets.conf` file and display a message accordingly. For example:

```
# Check if secrets.conf already exists
if os.path.exists('secrets.conf'):
    print("\nA secrets.conf file already exists. Please edit the existing file if you need to update your keys")

else:
    # Create the contents of the secrets.conf file
    contents = "[DEFAULT]\nGITHUB_TOKEN={}\nOPENAI_SDK={}".format(github_token, openai_sdk)

    # Write the contents to the secrets.conf file
    with open("secrets.conf", "w") as f:
        f.write(contents)
```

**Comment by TheSeanLavery** [comment]
> This code looks good overall. The help prompt provided is clear and concise, the variables created are aptly named and the file write process is handled correctly.
> 
> One addition that could improve the code would be to add a check for if a user has already created a `secrets.conf` file and display a message accordingly. For example:
> 
> ```
> # Check if secrets.conf already exists
> if os.path.exists('secrets.conf'):
>     print("\nA secrets.conf file already exists. Please edit the existing file if you need to update your keys")
> 
> else:
>     # Create the contents of the secrets.conf file
>     contents = "[DEFAULT]\nGITHUB_TOKEN={}\nOPENAI_SDK={}".format(github_token, openai_sdk)
> 
>     # Write the contents to the secrets.conf file
>     with open("secrets.conf", "w") as f:
>         f.write(contents)
> ```

No, I'd rather it just overwrite.

**Comment by CodeReviewGPT** [comment]
That's understandable, however it may be useful to let the user know if they already have a secrets.conf file so they can make sure they are not overwriting any existing changes they may have made.

**Comment by CodeReviewGPT** [comment]
This code looks good. The only thing I might suggest is adding a check after the user inputs the GitHub and OpenAI SDK keys to make sure that they are valid. This could be done by using the Github and OpenAI SDK APIs to ensure that the user has provided valid keys.

**Comment by CodeReviewGPT** [comment]
This code looks good overall. One suggestion would be to add a try/except block around the validation of the OpenAI SDK key, like is done with the GitHub token. As such, the code could be modified to the following:

```
# Validate the OpenAI SDK key
openai.api_key = openai_sdk
try:
    models = openai.Model.list()
    print("OpenAI SDK key is valid")
except openai.api_errors.ApiError as err:
    print("OpenAI SDK key is invalid")
```

**Comment by CodeReviewGPT** [comment]
**This code looks good overall. The only suggestion I would make is to add a comment to the beginning of the program to give an overview of what the program does. Additionally, I recommend adding comments to the code to make it more readable and explain what each section does. For example:**

```
# Prompt the user for their GitHub and OpenAI SDK keys
github_token = input("Enter your GitHub token: ")
openai_sdk = input("Enter your OpenAI SDK key: ")
``` 
to 
```
# Prompt the user for their GitHub and OpenAI SDK keys
github_token = input("Enter your GitHub token: ") # prompt user for GitHub token
openai_sdk = input("Enter your OpenAI SDK key: ") # prompt user for OpenAI SDK key
```

**Comment by TheSeanLavery** [comment]
> **This code looks good overall. The only suggestion I would make is to add a comment to the beginning of the program to give an overview of what the program does. Additionally, I recommend adding comments to the code to make it more readable and explain what each section does. For example:**
> 
> ```
> # Prompt the user for their GitHub and OpenAI SDK keys
> github_token = input("Enter your GitHub token: ")
> openai_sdk = input("Enter your OpenAI SDK key: ")
> ```
> 
> to
> 
> ```
> # Prompt the user for their GitHub and OpenAI SDK keys
> github_token = input("Enter your GitHub token: ") # prompt user for GitHub token
> openai_sdk = input("Enter your OpenAI SDK key: ") # prompt user for OpenAI SDK key
> ```

Hahah that is way too verbose. I can make a header comment for it though.

**Comment by CodeReviewGPT** [comment]
Thanks for the suggestion! I'll add a comment to the beginning of the program to give an overview of what the program does, as well as some comments to make the code more readable and explain what each section does.

**Pull request merged**
