### PR TITLE
basic PR reviewing

### PR DESCRIPTION
**Pull request by TheSeanLavery**
Basic functionality

### CODE REVIEW

**Comment by CodeReviewGPT** [comment]
This code looks good overall. It reads the secrets from a configuration file, sets up the necessary API keys, makes the necessary requests, and posts a comment on the pull request. However, it could be improved by adding better error handling and more robust logging.

**Comment by CodeReviewGPT** [comment]
##### This code should be changed in the following ways:
- The secrets should be stored in environment variables rather than in a configuration file.
- The `openai_token` variable should be renamed to something more descriptive. 
- The `headers` variable should be declared outside of the loop and reused in each iteration.
- The response from the request to get the list of changes for the pull request should be checked for an error before attempting to get the list of changes.
- The `newChanges` variable should be declared outside the loop and reset for each iteration.
- The `text` variable should be declared outside the loop and reset for each iteration.
- The `openai_response` variable should be declared outside the loop and reset for each iteration.
- The response from the request to post the comment should be checked for an error before printing the success message.
- The `print` statements should be replaced with `logging` statements.

**Comment by CodeReviewGPT** [comment]
This code looks like a basic PR reviewing system. However, there are a few issues that should be addressed:

- The comment in line 34 should be removed as it is not necessary.
- Line 35 should be changed to `text = title + "\n" + body + "\n" + (newChanges)` as it is a more efficient way to combine the strings.
- Line 51 should be changed to `openai_response = response["choices"][0]["text"].strip()` to remove any whitespace from the end of the response.
- Lines 55-62 should be refactored into a function to make the code more readable and easier to maintain. 
- Line 73 should be changed to `print(f"Error getting pull requests: {response.status_code} {response.reason}")` to make the error messaging more consistent.

**Comment by CodeReviewGPT** [comment]
This code looks generally fine, but there are a few changes that could be made to improve readability and efficiency. 

**Line 8**:
`config.read("secrets.conf")`

This line should be changed to use the `os.path.expandvars()` function. This will allow the code to use environment variables to access the configuration file.

**Lines 15-19**:
```
owner = "TheSeanLavery"
repo = "code-review-gpt"
issue_number = 1
```

These lines should be changed to use environment variables to store the owner, repository name, and issue number. This will make the code more flexible and easier to maintain.

**Lines 24-27**:
```
headers = {
    "Authorization": f"Token {github_token}",
    "Accept": "application/vnd.github+json",
    "Content-Type": "application/json"
}
```

The headers should be stored in a separate dictionary or configuration file. This will make the code more maintainable and easier to read. 

**

**Comment by TheSeanLavery** [comment]
I'll make a note and do these later

**Comment by CodeReviewGPT** [comment]
That sounds like a great plan! Let me know if you need any help.

**Pull request merged**
